#:import Clock kivy.clock.Clock

<MyDrawer>:
    screen: 'menu'
    enable_swiping: False

    BoxLayout:
        orientation: 'vertical'
        spacing: '10dp'
        padding: '8dp'

        MDIconButton:
            icon: 'arrow-collapse-left'
            halign: 'left'
            on_press: root.set_state("close")

        MDLabel:
            text: 'Classic games'
            halign: 'center'
            font_style: 'Headline'
            role: 'small'
            size_hint_y: None
            height: self.texture_size[1]
            font_name: 'fonts/magnetob'
            theme_text_color: 'Custom'
            text_color: app.theme_cls.primaryColor
        
        Image:
            source: 'images/icon.png'
            size_hint_y: None
            height: '150dp'
            

        MDList:
            MDListItem:
                on_release:
                    root.set_state("close")
                    root.screen = 'menu'
                MDListItemLeadingIcon:
                    icon: 'menu'
                MDListItemHeadlineText:
                    text: 'Main menu'

            MDListItem:
                on_release:
                    root.set_state("close")
                    app.open_settings()
                MDListItemLeadingIcon:
                    icon: 'cog'
                MDListItemHeadlineText:
                    text: 'Settings'

            MDListItem:
                on_release:
                    root.set_state("close")
                    root.open_help()
                MDListItemLeadingIcon:
                    icon: 'help-circle-outline'
                MDListItemHeadlineText:
                    text: 'Help'

            MDListItem:
                on_release:
                    root.set_state("close")
                    root.about()
                MDListItemLeadingIcon:
                    icon: 'information-outline'
                MDListItemHeadlineText:
                    text: 'About'

            MDListItem:
                on_release:
                    app.play('bye')
                    Clock.schedule_once(app.stop, 2)
                MDListItemLeadingIcon:
                    icon: 'logout'
                MDListItemHeadlineText:
                    text: 'Exit'


        
        ScrollView:
            MDList:
                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'pong'
                    MDListItemLeadingAvatar:
                        source: 'pong/images/icon.jpg'
                    MDListItemHeadlineText:
                        text: 'pong'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'ahorcado'
                    MDListItemLeadingAvatar:
                        source: 'ahorcado/images/icon.jpg'
                    MDListItemHeadlineText:
                        text: 'ahorcado'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'memory'
                    MDListItemLeadingAvatar:
                        source: 'memory/images/icon.png'
                    MDListItemHeadlineText:
                        text: 'memory'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'fifteen'
                    MDListItemLeadingAvatar:
                        source: 'game_15puzzle/images/icon.png'
                    MDListItemHeadlineText:
                        text: '15 puzzle'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = '2048'
                    MDListItemLeadingAvatar:
                        source: 'game_2048/images/icon.png'
                    MDListItemHeadlineText:
                        text: '2048'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'buscaminas'
                    MDListItemLeadingAvatar:
                        source: 'buscaminas/images/icon.png'
                    MDListItemHeadlineText:
                        text: 'buscaminas'

                MDListItem:
                    on_release:
                        root.set_state("close")
                        root.screen = 'snake'
                    MDListItemLeadingAvatar:
                        source: 'snake/images/icon.png'
                    MDListItemHeadlineText:
                        text: 'snake'
