<MyTile>:
    size_hint_y: None
    height: self.width
    on_release: app.root.ids.my_drawer.screen = root.screen

    MDSmartTileImage:
        source: root.source

    MDSmartTileOverlayContainer:
        adaptive_height: True
        padding: '8dp'
        md_bg_color: 0, 0, 0, .5

        MDLabel:
            text: root.txt
            theme_text_color: 'Custom'
            text_color: 1, 1, 1, 1
    
    
<Menu>:
    name: 'menu'
    
    BoxLayout:
        orientation: 'vertical'
    
        MDTopAppBar:
            MDTopAppBarLeadingButtonContainer:
                MDActionTopAppBarButton:
                    icon: 'menu'
                    on_release: app.root.ids.my_drawer.set_state('open')

            MDTopAppBarTitle:
                text: 'Classic Games'
            
        ScrollView:
        
            MDGridLayout:
                cols: 2
                adaptive_height: True
                padding: dp(25), dp(25)
                spacing: dp(25)
                
                MyTile:
                    txt: 'pong'
                    source: 'pong/images/icon.jpg'
                    screen: 'pong'
    
                MyTile:
                    txt: 'ahorcado'
                    source: 'ahorcado/images/icon.jpg'
                    screen: 'ahorcado'
                                
                MyTile:
                    txt: 'memory'
                    source: 'memory/images/icon.png'
                    screen: 'memory'
                                
                MyTile:
                    txt: '15 puzzle'
                    source: 'game_15puzzle/images/icon.png'
                    screen: 'fifteen'
    
                MyTile:
                    txt: '2048'
                    source: 'game_2048/images/icon.png'
                    screen: '2048'
    
                MyTile:
                    txt: 'buscaminas'
                    source: 'buscaminas/images/icon.png'
                    screen: 'buscaminas'

                MyTile:
                    txt: 'snake'
                    source: 'snake/images/icon.png'
                    screen: 'snake'
