site_name: classic_games
repo_name: https://github.com/osso73/classic_games
# theme: readthedocs
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Games:
      - games/pong.md
      - games/ahorcado.md
      - games/memory.md
      - games/15puzzle.md
  - About: about.md
